const enum DAISUI {
    "Alert",
    "Artboard",
    "Avatar",
    "Badge",
    "Bottom navigation",
    "Breadcrumbs",
    "Button group",
    "Button",
    "Card",
    "Carousel",
    "Checkbox",
    "Collapse",
    "Countdown",
    "Divider",
    "Drawer",
    "Dropdown",
    "Footer",
    "Hero",
    "Indicator",
    "Input group",
    "Text Input",
    "Kbd",
    "Link",
    "Mask",
    "Menu",
    "Code mockup",
    "Phone mockup",
    "Window mockup",
    "Modal",
    "Navbar",
    "Pagination",
    "Progress",
    "Radial progress",
    "Radio",
    "Range slider",
    "Rating",
    "Select",
    "Stack",
    "Stat",
    "Steps",
    "Swap",
    "Tabs",
    "Table",
    "Textarea",
    "Toast",
    "Toggle",
    "Tooltip"
}

interface HomePage {}